ui: mocha-bdd
server: ./test/support/server.js
browsers:
  - name: chrome
    version: 29..latest
# Firefox disabled for now because it can cause infinite wait loops when
# running any tests
#  - name: firefox
#    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 10
    platform: Windows 2012
  - name: ie
    version: [6..9, latest]
  - name: iphone
    version: oldest..latest
