# trusted publishing: https://docs.npmjs.com/trusted-publishers#for-github-actions
# staged publishing: https://docs.npmjs.com/staged-publishing

name: Publish

on:
  push:
    tags:
      - 'socket.io-parser@*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Use Node.js 26
        uses: actions/setup-node@v6
        with:
          node-version: 26
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Publish package
        run: npm stage publish --tag v2-latest
